### Importar as bibliotecas

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Dados de respostas

In [71]:
# Carregar os dados das respostas do POSCOMP 2016
dados_respostas_2016 = pd.read_csv('dados/respostas_poscomp/exportacao_respostas_poscomp_2016.csv', sep=';', encoding='utf-8')
dados_respostas_2017 = pd.read_csv('dados/respostas_poscomp/exportacao_respostas_poscomp_2017.csv', sep=';', encoding='utf-8')
dados_respostas_2018 = pd.read_csv('dados/respostas_poscomp/exportacao_respostas_poscomp_2018.csv', sep=';', encoding='utf-8')
dados_respostas_2019 = pd.read_csv('dados/respostas_poscomp/exportacao_respostas_poscomp_2019.csv', sep=';', encoding='utf-8')

In [26]:
dados_respostas_2016.columns

Index(['NUM', 'NÚMERO DE INSCRIÇÃO', 'SITUAÇÃO', '1', '2', '3', '4', '5', '6',
       '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18',
       '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30',
       '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42',
       '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54',
       '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66',
       '67', '68', '69', '70'],
      dtype='object')

In [72]:
dados_respostas_2016.set_index('NÚMERO DE INSCRIÇÃO')
dados_respostas_2017.set_index('NÚMERO DE INSCRIÇÃO')
dados_respostas_2018.set_index('NÚMERO DE INSCRIÇÃO')
dados_respostas_2019.set_index('NÚMERO DE INSCRIÇÃO')

,NUM,NOME CANDIDATO,SALA,SITUAÇÃO,1,2,3,4,5,6,...,61,62,63,64,65,66,67,68,69,70
NÚMERO DE INSCRIÇÃO,,,,,,,,,,,,,,,,,,,,,
51801393615,"1,05101E+11",Aarao Melo Lopes,5100,Presente,A,B,D,E,E,B,...,B,D,D,A,B,D,E,C,B,A
51801392147,"1,01601E+11",Abner Fontebom Bissolli Costa,1600,Presente,A,B,D,E,B,B,...,B,B,E,D,C,A,E,E,C,B
51801384165,"1,02001E+11",Acquila Santos Rocha,2000,Presente,A,A,D,E,A,C,...,B,D,A,A,A,C,E,A,C,E
51801397157,"1,05601E+11",Adailton Saraiva,5600,Presente,A,B,C,C,D,C,...,B,E,C,A,A,A,E,C,C,C
51801377987,"1,05101E+11",Adauton Machado Heringer,5100,Presente,A,B,D,E,E,B,...,B,E,B,A,B,A,C,D,C,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51801396055,"1,05602E+11",Yuri Moraski Batista,5601,Presente,A,B,D,B,C,B,...,B,A,D,A,C,C,E,A,E,E
51801354647,"1,03601E+11",Yuri Silva Vaz,3600,Presente,C,B,D,E,E,B,...,B,A,D,D,C,C,E,A,C,A
51801393821,"1,00402E+11",yuri vladimir huallpa vargas,401,Presente,A,B,D,E,E,B,...,B,NaN,NaN,A,C,A,B,D,NaN,E
51801354273,"1,00201E+11",Yury Alencar Lima,200,Ausente,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
51801366900,"1,05106E+11",Zoltán Hirata Jetsmen,5105,Ausente,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-

In [73]:
dados_respostas_2016 = dados_respostas_2016.assign(ANO='2016')
dados_respostas_2017 = dados_respostas_2017.assign(ANO='2017')
dados_respostas_2018 = dados_respostas_2018.assign(ANO='2018')
dados_respostas_2019 = dados_respostas_2019.assign(ANO='2019')

In [80]:
# Unir as tabelas de dados_respostas de todos os anos
dados_respostas_1 = pd.concat([dados_respostas_2016, dados_respostas_2017, dados_respostas_2018, dados_respostas_2019], axis=0)
dados_respostas_1 = dados_respostas_1.drop(columns=['NOME CANDIDATO','SALA'])

## Dados de Homologação

In [100]:
dados_homologados_2016 = pd.read_csv("dados/homologação_poscomp/homologados_dados_contatos_poscomp_2016.csv", sep=';', encoding='utf-8')
dados_homologados_2017 = pd.read_csv("dados/homologação_poscomp/homologados_dados_contatos_poscomp_2017.csv", sep=';', encoding='utf-8')
dados_homologados_2018 = pd.read_csv("dados/homologação_poscomp/homologados_dados_contatos_poscomp_2018.csv", sep=';', encoding='utf-8')
dados_homologados_2019 = pd.read_csv("dados/homologação_poscomp/homologados_dados_contatos_poscomp_2019.csv", sep=';', encoding='utf-8')

In [80]:
# Dados da homologação dos candidatos POSCOMP 2016
# dados_homologados_2016 = dados_homologados_2016.set_index('ESTADO')
dados_homologados_2016.columns

Index(['NOME', 'CPF', 'DATA NASC.', 'SEXO', 'TIPO DE DOCUMENTO', 'DOCUMENTO',
       'NOME DO PAI', 'NOME DA MÃE', 'ENDERECO.', 'NUMERO', 'COMPL.', 'BAIRRO',
       'CIDADE', 'ESTADO', 'CEP', 'EMAIL', 'DDD', 'FONE', 'DDD CEL', 'CELULAR',
       'SENHA', 'INSCRICAO', 'DATA INSCRIÇÃO', 'CARGO', 'CÓDIGO', 'DS CARGO',
       'DEFICIENTE', 'LOCAL DE PROVA', 'NECESSIDADES ESPECIAIS',
       'DESCRICAO DA NECESSIDADE', 'ESTRANGEIRO'],
      dtype='object')

In [102]:
dados_homologados_2016 = dados_homologados_2016.assign(ANO='2016')
dados_homologados_2017 = dados_homologados_2017.assign(ANO='2017')
dados_homologados_2018 = dados_homologados_2018.assign(ANO='2018')
dados_homologados_2019 = dados_homologados_2019.assign(ANO='2019')

In [103]:
dados_homologados = pd.concat([dados_homologados_2016, dados_homologados_2017, dados_homologados_2018, dados_homologados_2019], axis=0)
dados_homologados = dados_homologados.drop(columns=['NOME','CPF', 'DATA NASC.', 'TIPO DE DOCUMENTO', 'DOCUMENTO','NOME DO PAI', 
                                                    'NOME DA MÃE', 'EMAIL', 'DDD', 'FONE', 'DDD CEL', 'CELULAR', 'SENHA', 'DATA INSCRIÇÃO',
                                                    'DEFICIENTE', 'NECESSIDADES ESPECIAIS', 'DESCRICAO DA NECESSIDADE', 'ESTRANGEIRO', 
                                                    'DS CARGO', 'COMPL.'])

In [106]:
dados_homologados.set_index('ESTADO')

,SEXO,ENDERECO.,NUMERO,BAIRRO,CIDADE,CEP,INSCRICAO,CARGO,CÓDIGO,LOCAL DE PROVA,ANO
ESTADO,,,,,,,,,,,
OU,M,Pampas de Polanco,16,Ramiro Priale,Arequipa,05105-1,39401673171-6,1-Mestrado/Doutorado,1,Arequipa - PERU,2016
CE,M,Mário Studart,380,Jacarecanga,Fortaleza,60326-060,39401645886-1,1-Mestrado/Doutorado,1,Fortaleza - CE,2016
RS,M,Avenida da Azenha,324,Azenha,Porto Alegre,90160004,39401663587-8,1-Mestrado/Doutorado,1,Campina Grande - PB,2016
SP,M,Gregório Aversa,450,Recreio São Judas Tadeu,São Carlos,13571-260,39401651770-6,1-Mestrado/Doutorado,1,São Carlos - SP,2016
PA,M,Augusto Montenegro,200,Parque Verde,Belém,66635-110,39401671273-0,1-Mestrado/Doutorado,1,Belém - PA,2016
...,...,...,...,...,...,...,...,...,...,...,...
ES,M,Rua Piratininga,33,Praia da Costa,Vila Velha,29101-220,51801396055-5,1-Mestrado/Doutorado,1,Vitória/ES,2019
RS,M,Avenida São Francisco de Paula,2138,Areal,Pelotas,96080-730,51801354647-6,1-Mestrado/Doutorado,1,Pelotas/RS,2019
OU,M,jv tablon del niño jesus - san jeronimo,328,san jeronimo,cusco,08000-,51801393821-0,1-Mestrado/Doutorado,1,Arequipa/PERU,2019
RS,M,Rua Onófrio Lemos,114,Ibirapuitã,Alegrete,97546260,51801354273-1,1-Mestrado/Doutorado,1,Alegrete/RS,2019
SP,M,Rua Soldado Vital Fortuna,96,Vila Itapegica,Guarulhos,07043-160,51801366900-3,1-Mestrado/Doutorado,1,São Paulo/SP,2019

## Notas das respostas

#### Base de 2016

In [130]:
dados_notasRespostas_2016 = pd.read_csv("dados/notas_poscomp/Notas_poscomp_2016.csv", sep=';', encoding='utf-8')
dados_notasRespostas_2017 = pd.read_csv("dados/notas_poscomp/Notas_poscomp_2017.csv", sep=';', encoding='utf-8')
dados_notasRespostas_2018 = pd.read_csv("dados/notas_poscomp/Notas_poscomp_2018.csv", sep=';', encoding='utf-8')
dados_notasRespostas_2019 = pd.read_csv("dados/notas_poscomp/Notas_poscomp_2019.csv", sep=';', encoding='utf-8')

In [131]:
dados_notasRespostas_2016_processadas = dados_notasRespostas_2016.drop(columns=['CONCURSO', 'NOME', 'DATA NASC', 'CPF', 'DOCUMENTO',
                                                            'NEC ESP', 'HIPO','DEF', 'AFRO', 'INDIO', 'COD CARGO', 'CÓD. ESPECIALIDADE',
                                                         'PRESENTE DIA1','PRESENTE DIA2', 'PRESENTE DIA3', 'PARTICIPAÇÃO EM JÚRI', 
                                                            'NOTA TOTAL Prova Discursiva',' OBSERVAÇÃO Prova Discursiva', 'ESTRANGEIRO'])

In [132]:
dados_notasRespostas_2016_processadas.columns

Index(['CARGO', 'ESPECIALIDADE', 'INSCRICAO', 'IDENTIFICADOR',
       'ACERTOS Matemática Discreta', 'NOTA Matemática Discreta',
       'ACERTOS Cálculo Diferencial Integral',
       'NOTA Cálculo Diferencial Integral', 'ACERTOS Álgebra Linear',
       'NOTA Álgebra Linear', 'ACERTOS Geometria Analítica',
       'NOTA Geometria Analítica', 'ACERTOS Análise Combinatória',
       'NOTA Análise Combinatória', 'ACERTOS Probabilidade e Estatística',
       'NOTA Probabilidade e Estatística', 'ACERTOS Lógica Matemática',
       'NOTA Lógica Matemática', 'ACERTOS Organização de Arquivos e Dados',
       'NOTA Organização de Arquivos e Dados',
       'ACERTOS Técnicas de Programação', 'NOTA Técnicas de Programação',
       'ACERTOS Circuitos Digitais', 'NOTA Circuitos Digitais',
       'ACERTOS Análise de Algoritmos', 'NOTA Análise de Algoritmos',
       'ACERTOS Teoria dos Grafos', 'NOTA Teoria dos Grafos',
       'ACERTOS Linguagens Formais, Autômatos e Computabilidade',
       'NOTA Linguagens Formais, Autômatos e Computabilidade',
       'ACERTOS Algoritmos e Estruturas de Dados',
       'NOTA Algoritmos e Estruturas de Dados',
       'ACERTOS Linguagens de Programação', 'NOTA Linguagens de Programação',
       'ACERTOS Sistemas Operacionais', 'NOTA Sistemas Operacionais',
       'ACERTOS Arquitetura e Organização de Computadores',
       'NOTA Arquitetura e Organização de Computadores',
       'ACERTOS Rede de Computadores', 'NOTA Rede de Computadores',
       'ACERTOS Computação Gráfica', 'NOTA Computação Gráfica',
       'ACERTOS Inteligência Artificial', 'NOTA Inteligência Artificial',
       'ACERTOS Engenharia de Software', 'NOTA Engenharia de Software',
       'ACERTOS Sistemas Distribuídos', 'NOTA Sistemas Distribuídos',
       'ACERTOS Compiladores', 'NOTA Compiladores',
       'ACERTOS Processamento de Imagens', 'NOTA Processamento de Imagens',
       'ACERTOS Banco de Dados', 'NOTA Banco de Dados', 'ACERTOS TO',
       'NOTA TOTAL TO'],
      dtype='object')

## Salvar dados

In [77]:
dados_respostas_1.to_csv('dados/respostas_poscomp/dados_respostas.csv')

In [92]:
dados_homologados.to_csv('dados/homologação_poscomp/dados_homologados.csv')

In [133]:
dados_notasRespostas_2016_processadas.to_csv('dados/notas_poscomp/dados_notasRespostas.csv')